### ISSUE TITLE
LightsHUD - Bug - Module doesn't load

### ISSUE THREAD

**Issue by Zamrod** [Malekal4699/LightsHUD#17]
**Describe the bug**
Running V9 245 and Pathfinder 2e 3.2.2.10109, and LightsHUD 1.0.5 the module doesn't appear in settings and the HUD doesn't appear. The console throws the following error:
```
foundry.js:2144 
        
       Uncaught (in promise) Error: This is not a registered game setting
[Detected 1 package: LightsHUD]
    at ClientSettings.get (foundry.js:2144:42)
    at Function.addLightsHUDButtons (modules/LightsHUD/scripts/LightsHUD.js:54:43)
    at modules/LightsHUD/scripts/LightsHUD.js:1097:15
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at TokenHUD._render (foundry.js:3117:13)
    at async TokenHUD._render (foundry.js:52457:4)
```

**Comment by Sasmira** [comment]
Si ca peut aider, j'ai un message des que je fais un clic droit sur le personnage afin de faire apparaitre les options
<img src="https://puu.sh/IFCRJ/1c42e4c15c.png" >

**Comment by Malekal4699** [comment]
Fixed.
